# Generated by Django 4.1.3 on 2022-11-08 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Liked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_playlist", models.BooleanField()),
                ("username_creator", models.CharField(max_length=200)),
                ("playlist_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=200)),
                ("song_length", models.DurationField()),
                ("artist_name", models.CharField(max_length=200)),
                ("song_genre", models.CharField(max_length=200)),
                ("album", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_creator", models.CharField(max_length=200)),
                ("isFriend", models.BooleanField()),
                ("friend_name", models.CharField(max_length=100)),
                ("isFavoriteFriend", models.BooleanField()),
                ("favorite_genre", models.CharField(max_length=200)),
                ("favorite_artist", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
                ("isFavoriteSong", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playlist_name", models.CharField(max_length=200)),
                ("isPrivate", models.BooleanField()),
                ("playlist_description", models.CharField(max_length=200)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_playlist",
                        to="mixtape.user",
                    ),
                ),
                (
                    "likes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_playlist",
                        to="mixtape.user",
                    ),
                ),
                (
                    "song_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mixtape.song"
                    ),
                ),
            ],
        ),
    ]
