# Generated by Django 4.1.3 on 2022-11-19 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mixtape", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Liked",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="song_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="isFavoriteFriend",
        ),
        migrations.RemoveField(
            model_name="user",
            name="isFavoriteSong",
        ),
        migrations.RemoveField(
            model_name="user",
            name="isFriend",
        ),
        migrations.AddField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(to="mixtape.song"),
        ),
        migrations.AddField(
            model_name="song",
            name="isFavoriteSong",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="likes",
            field=models.ManyToManyField(to="mixtape.user"),
        ),
        migrations.AddField(
            model_name="user",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="likes",
        ),
        migrations.AddField(
            model_name="playlist",
            name="likes",
            field=models.ManyToManyField(to="mixtape.user"),
        ),
    ]
